name: 'RPM Build'
description: 'Build RPMs from spec file and upload it as Artifact or Release Asset'
author: 'carlospeon@gmail.com'

inputs: 
  spec:
    description: 'path to the spec file'
    required: true
  version:
    description: 'rpm version'
    required: true
  release:
    description: 'rpm release'
    required: false
    default: 1
  arch:
    description: 'build architecture'
    required: false
    default: x86_64

outputs:
  rpms_path:
    description: 'path to RPMS directory'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'package'
  color: 'red'

