name: 'buildrpm'
description: 'Build RPMs from spec file and upload it as Artifact or Release Asset'
author: 'carlospeon@gmail.com'

inputs: 
  spec:
    description: 'path to the spec file'
    required: true
  version:
    description: 'rpm version that will be defined in rpmbuild'
    required: true
  clean:
    description: 'clean rpmbuild environment before build'
    required: false
    default: false

outputs:
  rpms_path:
    description: 'path to RPMS directory'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'package'
  color: 'red'

